### ISSUE TITLE
ユーザーカスタムサブコマンドの実装

### ISSUE THREAD

**Issue by kechigon** [3-shake/alert-menta#26]
コマンド名、システムプロンプトを指定できる

**Comment by nwiizo** [comment]
## 実装完了

`.alert-menta.user.yaml` の `ai.commands` セクションで任意のカスタムコマンドを定義可能です。

```yaml
ai:
  commands:
    my_custom_command:
      description: "カスタムコマンドの説明"
      system_prompt: "カスタムシステムプロンプト"
      require_intent: false
```
