### ISSUE TITLE
.alert-menta.user.yamlにvertexAIの設定がべた書きになっている

### ISSUE THREAD

**Issue by kechigon** [3-shake/alert-menta#30]
# Why

以下のように現状の実装ではべた書きする仕様になっている。

```jsx
  vertexai:
    project: "gen-ai-lab-391309"
    location: "us-central1"
    model: "gemini-1.5-flash-001"
```

公開しないに越したことはない。

# What

環境変数で渡す→askとintentみたいにvertexを使うときだけ必要な引数として渡す

.envファイル→設定ファイルの設定ファイルみたいでややこしい

**Comment by nwiizo** [comment]
## 対応方法

環境変数で機密情報を渡すことが可能です：

```yaml
ai:
  vertexai:
    project: "${VERTEX_PROJECT}"  # 環境変数から取得
```

または CLI フラグで渡すことも可能。現状の実装で対応可能なためクローズ。
